on:
  schedule:
    - cron: '1,5,10,15,30,35,40,45,50,55 * * * *' #每个小时的第1,30分钟刷新一次
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'refresh b4a app'
        run: bash ./b4app.sh