name: Install ToDesk and Send Screenshot
on:
  push:
    paths:
      - '.github/workflows/todesk.yml'

jobs:
  unzip_and_screenshot:
    timeout-minutes: 70
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: ""
    runs-on: windows-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r .\requirements.txt
      - name: Take_Screenshot_windows
        run: |
          python -c "import pyautogui; import time; time.sleep(1); pyautogui.hotkey('win','d'); time.sleep(1);"           
      # 3. 启动ToDesk并等待5秒
      - name: Run ToDesk and Wait
        shell: pwsh
        run: |
          Start-Process ".\ask.exe"

          Start-Sleep -Seconds 9  # 延迟5秒确保界面加载
          python -c "import pyautogui; import time; time.sleep(1); pyautogui.moveTo(646,547); pyautogui.click(); time.sleep(2);pyautogui.moveTo(700,618); pyautogui.click(); time.sleep(15);" 
      # 4. 屏幕截图（使用Windows内置工具）
      - name: Take Screenshot
        shell: pwsh
        run: |
          $screenshotPath = "$env:RUNNER_TEMP\screenshot.png"
          Add-Type -AssemblyName System.Windows.Forms
          [Windows.Forms.SendKeys]::SendWait('{PRTSC}')  # 模拟按下PrintScreen键
          $image = [Windows.Forms.Clipboard]::GetImage()
          $image.Save($screenshotPath, [Drawing.Imaging.ImageFormat]::Png)
          echo "SCREENSHOT_PATH=$screenshotPath" >> $env:GITHUB_ENV

      # 5. 通过邮件发送截图
      - name: send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: 1971902975@qq.com
          password: otxoismbtaqucddg
          from: github action
          to: nooneb1998@foxmail.com
          subject: 运行截图
          body: "你好"
          attachments: ${{ env.SCREENSHOT_PATH }}  # 附加截图
      - name: Hold for 60 minutes
        run: Start-Sleep -Seconds 3600
        timeout-minutes: 65
    