name: Install ToDesk on Windows
on:
  push:
    paths:
      - '.github/workflows/todesk.yml'  # 监听特定文件

jobs:
  unzip:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Direct Unzip to Current Directory
        shell: pwsh
        run: Expand-Archive -Path "ToDesk_4.6.0.1_Green.zip" -DestinationPath "." -Force
